services:
  omada:
    build:
      context: .
      args:
        LIB_URL: https://github.com/damoun/docker-omada-controller/releases/download/v6.1.0.19/lib.tar.gz
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/omada
      - OMADA_PORT_DISCOVERY=30001
    ports:
      - 8088:8088
      - 8043:8043
      - 8843:8843
      - 30001:30001/udp
  mongo:
    image: mongo:8.0
    ports:
      - '27017:27017'
